import { Vehicle } from "@/lib/types";

export const vehicles: Vehicle[] = [
  {
    id: "bronco",
    ownershipStatus: "own",
    nickname: "Trail Bronco",
    year: 2023,
    make: "Ford",
    model: "Bronco",
    trim: "Outer Banks",
    vin: "1FMDE5BH4PLA00001",
    powertrain: "gas",
    image:
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80",
    telemetry: {
      capturedAt: "2026-03-07T19:42:00Z",
      odometerMiles: 18422,
      batteryOrFuelPercent: 62,
      latitude: 40.741,
      longitude: -73.989,
      speedMph: 0,
      ignitionOn: false,
      source: "mock-smartcar"
    },
    valuationHistory: [
      {
        capturedAt: "2026-02-08T12:00:00Z",
        marketValueUsd: 42100,
        changeUsd: 0,
        changePercent: 0,
        confidence: "high",
        source: "mock-marketcheck"
      },
      {
        capturedAt: "2026-02-22T12:00:00Z",
        marketValueUsd: 41750,
        changeUsd: -350,
        changePercent: -0.83,
        confidence: "high",
        source: "mock-marketcheck"
      },
      {
        capturedAt: "2026-03-07T12:00:00Z",
        marketValueUsd: 41280,
        changeUsd: -470,
        changePercent: -1.13,
        confidence: "high",
        source: "mock-marketcheck"
      }
    ],
    maintenance: [
      {
        id: "bronco-oil",
        title: "Synthetic oil and filter service",
        category: "engine",
        status: "due",
        dueDate: "2026-03-20",
        dueMileage: 19000,
        estimatedCostUsd: 129,
        providerRecommendation: "6 months or 5,000 miles",
        canScheduleOnline: false,
        recurrenceMiles: 5000,
        recurrenceDays: 180,
        autoGenerated: true
      },
      {
        id: "bronco-tires",
        title: "Rotate tires and inspect alignment",
        category: "tires",
        status: "upcoming",
        dueDate: "2026-04-18",
        dueMileage: 20000,
        estimatedCostUsd: 85,
        providerRecommendation: "Every 7,500 miles",
        canScheduleOnline: false,
        recurrenceMiles: 7500,
        autoGenerated: true
      }
    ],
    alerts: [
      {
        id: "bronco-move",
        title: "Movement watch",
        body: "Vehicle has not moved in 6 days. Consider a battery tender or short drive cycle.",
        severity: "warning",
        createdAt: "2026-03-07T18:00:00Z",
        channelSuggestions: ["push", "email"]
      }
    ],
    parts: [
      {
        id: "bronco-filter",
        query: "2023 Ford Bronco oil filter",
        title: "Motorcraft FL-500S Oil Filter",
        marketplace: "Amazon",
        priceUsd: 8.97,
        primeEligible: true,
        fitmentConfidence: "high",
        url: "https://www.amazon.com/"
      }
    ]
  },
  {
    id: "taycan",
    ownershipStatus: "own",
    nickname: "Daily EV",
    year: 2022,
    make: "Porsche",
    model: "Taycan",
    trim: "4S",
    vin: "WP0AB2Y10NSA00002",
    powertrain: "ev",
    image:
      "https://images.unsplash.com/photo-1553440569-bcc63803a83d?auto=format&fit=crop&w=1200&q=80",
    telemetry: {
      capturedAt: "2026-03-07T20:05:00Z",
      odometerMiles: 26310,
      batteryOrFuelPercent: 48,
      latitude: 40.758,
      longitude: -73.9855,
      speedMph: 34,
      ignitionOn: true,
      source: "mock-smartcar"
    },
    valuationHistory: [
      {
        capturedAt: "2026-02-08T12:00:00Z",
        marketValueUsd: 78600,
        changeUsd: 0,
        changePercent: 0,
        confidence: "medium",
        source: "mock-marketcheck"
      },
      {
        capturedAt: "2026-02-22T12:00:00Z",
        marketValueUsd: 77920,
        changeUsd: -680,
        changePercent: -0.87,
        confidence: "medium",
        source: "mock-marketcheck"
      },
      {
        capturedAt: "2026-03-07T12:00:00Z",
        marketValueUsd: 77110,
        changeUsd: -810,
        changePercent: -1.04,
        confidence: "medium",
        source: "mock-marketcheck"
      }
    ],
    maintenance: [
      {
        id: "taycan-brake",
        title: "Brake fluid inspection",
        category: "brakes",
        status: "upcoming",
        dueDate: "2026-04-02",
        dueMileage: null,
        estimatedCostUsd: 220,
        providerRecommendation: "Annually",
        canScheduleOnline: false,
        recurrenceDays: 365,
        autoGenerated: true
      },
      {
        id: "taycan-cabin",
        title: "Cabin air filter replacement",
        category: "filters",
        status: "scheduled",
        dueDate: "2026-03-14",
        dueMileage: null,
        estimatedCostUsd: 145,
        providerRecommendation: "Every 20,000 miles",
        canScheduleOnline: false,
        recurrenceMiles: 20000,
        autoGenerated: true
      }
    ],
    alerts: [
      {
        id: "taycan-charge",
        title: "Charging reminder",
        body: "Battery is below 50% and tomorrow's calendar indicates a long drive.",
        severity: "info",
        createdAt: "2026-03-07T19:55:00Z",
        channelSuggestions: ["push"]
      }
    ],
    parts: [
      {
        id: "taycan-mat",
        query: "2022 Porsche Taycan floor mats",
        title: "All-weather floor liner set",
        marketplace: "Amazon",
        priceUsd: 189,
        primeEligible: true,
        fitmentConfidence: "medium",
        url: "https://www.amazon.com/"
      }
    ]
  }
];
