export type Powertrain = "gas" | "diesel" | "hybrid" | "ev";
export type VehicleOwnershipStatus = "own" | "owned" | "watching";
export type AlertSeverity = "info" | "warning" | "critical";
export type MaintenanceStatus = "upcoming" | "due" | "overdue" | "scheduled";
export type MaintenanceCategory =
  | "engine"
  | "tires"
  | "brakes"
  | "fluids"
  | "filters"
  | "battery"
  | "inspection"
  | "general";

export interface TelemetrySnapshot {
  capturedAt: string;
  odometerMiles: number;
  batteryOrFuelPercent: number;
  latitude: number;
  longitude: number;
  speedMph: number;
  ignitionOn: boolean;
  source: string;
}

export interface ValuationPoint {
  capturedAt: string;
  marketValueUsd: number;
  changeUsd: number;
  changePercent: number;
  confidence: "low" | "medium" | "high";
  source: string;
  comparableCount?: number | null;
  lastSeenAt?: string | null;
}

export interface MaintenanceTask {
  id: string;
  title: string;
  category: MaintenanceCategory;
  status: MaintenanceStatus;
  dueDate: string;
  dueMileage: number | null;
  estimatedCostUsd: number;
  providerRecommendation: string;
  canScheduleOnline: boolean;
  notes?: string | null;
  recurrenceMiles?: number | null;
  recurrenceDays?: number | null;
  completedAt?: string | null;
  completedMileage?: number | null;
  autoGenerated?: boolean;
}

export interface Alert {
  id: string;
  title: string;
  body: string;
  severity: AlertSeverity;
  createdAt: string;
  channelSuggestions: string[];
}

export interface PartListing {
  id: string;
  query: string;
  title: string;
  marketplace: string;
  priceUsd: number;
  primeEligible: boolean;
  fitmentConfidence: "low" | "medium" | "high";
  url: string;
}

export interface Vehicle {
  id: string;
  ownershipStatus: VehicleOwnershipStatus;
  nickname: string;
  year: number;
  make: string;
  model: string;
  trim: string;
  vin: string;
  powertrain: Powertrain;
  image: string;
  sourceUrl?: string | null;
  watchNotes?: string | null;
  lifecycleNotes?: string | null;
  acquisitionDate?: string | null;
  dispositionDate?: string | null;
  purchasePriceUsd?: number | null;
  salePriceUsd?: number | null;
  targetPriceUsd?: number | null;
  targetMileage?: number | null;
  telemetry: TelemetrySnapshot;
  valuationHistory: ValuationPoint[];
  maintenance: MaintenanceTask[];
  alerts: Alert[];
  parts: PartListing[];
}
